/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// Algorithm
    /// </summary>
    [DataContract]
    public partial class Algorithm :  IEquatable<Algorithm>, IValidatableObject
    {
        /// <summary>
        /// Defines ProblemType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProblemTypeEnum
        {
            
            /// <summary>
            /// Enum Min for value: min
            /// </summary>
            [EnumMember(Value = "min")]
            Min = 1,
            
            /// <summary>
            /// Enum MinMax for value: min-max
            /// </summary>
            [EnumMember(Value = "min-max")]
            MinMax = 2
        }

        /// <summary>
        /// Gets or Sets ProblemType
        /// </summary>
        [DataMember(Name="problem_type", EmitDefaultValue=false)]
        public ProblemTypeEnum? ProblemType { get; set; }
        /// <summary>
        /// Defines Objective
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ObjectiveEnum
        {
            
            /// <summary>
            /// Enum Transporttime for value: transport_time
            /// </summary>
            [EnumMember(Value = "transport_time")]
            Transporttime = 1,
            
            /// <summary>
            /// Enum Completiontime for value: completion_time
            /// </summary>
            [EnumMember(Value = "completion_time")]
            Completiontime = 2
        }

        /// <summary>
        /// Gets or Sets Objective
        /// </summary>
        [DataMember(Name="objective", EmitDefaultValue=false)]
        public ObjectiveEnum? Objective { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Algorithm" /> class.
        /// </summary>
        /// <param name="ProblemType">ProblemType.</param>
        /// <param name="Objective">Objective.</param>
        public Algorithm(ProblemTypeEnum? ProblemType = default(ProblemTypeEnum?), ObjectiveEnum? Objective = default(ObjectiveEnum?))
        {
            this.ProblemType = ProblemType;
            this.Objective = Objective;
        }
        


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Algorithm {\n");
            sb.Append("  ProblemType: ").Append(ProblemType).Append("\n");
            sb.Append("  Objective: ").Append(Objective).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Algorithm);
        }

        /// <summary>
        /// Returns true if Algorithm instances are equal
        /// </summary>
        /// <param name="input">Instance of Algorithm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Algorithm input)
        {
            if (input == null)
                return false;

            return 
                (
                    ProblemType == input.ProblemType ||
                    (ProblemType != null &&
                    ProblemType.Equals(input.ProblemType))
                ) && 
                (
                    Objective == input.Objective ||
                    (Objective != null &&
                    Objective.Equals(input.Objective))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (ProblemType != null)
                    hashCode = hashCode * 59 + ProblemType.GetHashCode();
                if (Objective != null)
                    hashCode = hashCode * 59 + Objective.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
