/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// A found path
    /// </summary>
    [DataContract]
    public partial class IsochroneResponsePolygon :  IEquatable<IsochroneResponsePolygon>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IsochroneResponsePolygon" /> class.
        /// </summary>
        /// <param name="Properties">Properties.</param>
        /// <param name="Type">Type.</param>
        /// <param name="Geometry">Geometry.</param>
        public IsochroneResponsePolygon(IsochroneResponsePolygonProperties Properties = default(IsochroneResponsePolygonProperties), string Type = default(string), IsochroneResponsePolygonGeometry Geometry = default(IsochroneResponsePolygonGeometry))
        {
            this.Properties = Properties;
            this.Type = Type;
            this.Geometry = Geometry;
        }
        
        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name="properties", EmitDefaultValue=false)]
        public IsochroneResponsePolygonProperties Properties { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Geometry
        /// </summary>
        [DataMember(Name="geometry", EmitDefaultValue=false)]
        public IsochroneResponsePolygonGeometry Geometry { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IsochroneResponsePolygon {\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Geometry: ").Append(Geometry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as IsochroneResponsePolygon);
        }

        /// <summary>
        /// Returns true if IsochroneResponsePolygon instances are equal
        /// </summary>
        /// <param name="input">Instance of IsochroneResponsePolygon to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IsochroneResponsePolygon input)
        {
            if (input == null)
                return false;

            return 
                (
                    Properties == input.Properties ||
                    (Properties != null &&
                    Properties.Equals(input.Properties))
                ) && 
                (
                    Type == input.Type ||
                    (Type != null &&
                    Type.Equals(input.Type))
                ) && 
                (
                    Geometry == input.Geometry ||
                    (Geometry != null &&
                    Geometry.Equals(input.Geometry))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Properties != null)
                    hashCode = hashCode * 59 + Properties.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Geometry != null)
                    hashCode = hashCode * 59 + Geometry.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
