/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// Additional information for your request
    /// </summary>
    [DataContract]
    public partial class ResponseInfo :  IEquatable<ResponseInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseInfo" /> class.
        /// </summary>
        /// <param name="Copyrights">Copyrights.</param>
        /// <param name="Took">Took.</param>
        public ResponseInfo(List<string> Copyrights = default(List<string>), double? Took = default(double?))
        {
            this.Copyrights = Copyrights;
            this.Took = Took;
        }
        
        /// <summary>
        /// Gets or Sets Copyrights
        /// </summary>
        [DataMember(Name="copyrights", EmitDefaultValue=false)]
        public List<string> Copyrights { get; set; }

        /// <summary>
        /// Gets or Sets Took
        /// </summary>
        [DataMember(Name="took", EmitDefaultValue=false)]
        public double? Took { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseInfo {\n");
            sb.Append("  Copyrights: ").Append(Copyrights).Append("\n");
            sb.Append("  Took: ").Append(Took).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ResponseInfo);
        }

        /// <summary>
        /// Returns true if ResponseInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ResponseInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    Copyrights == input.Copyrights ||
                    Copyrights != null &&
                    Copyrights.SequenceEqual(input.Copyrights)
                ) && 
                (
                    Took == input.Took ||
                    (Took != null &&
                    Took.Equals(input.Took))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Copyrights != null)
                    hashCode = hashCode * 59 + Copyrights.GetHashCode();
                if (Took != null)
                    hashCode = hashCode * 59 + Took.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
