  /* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// A found path
    /// </summary>
    [DataContract]
    public partial class RouteResponsePath : IEquatable<RouteResponsePath>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteResponsePath" /> class.
        /// </summary>
        /// <param name="distance">The total distance of the route, in meter.</param>
        /// <param name="time">The total time of the route, in ms.</param>
        /// <param name="ascend">Ascend.</param>
        /// <param name="descend">The total descend (downhill) of the route, in meter.</param>
        /// <param name="points">Points.</param>
        /// <param name="pointsEncoded">Is true if the points are encoded, if not paths[0].points contains the geo json of the path (then order is lon,lat,elevation), which is easier to handle but consumes more bandwidth compared to encoded version.</param>
        /// <param name="bbox">The bounding box of the route, format &lt;br&gt; minLon, minLat, maxLon, maxLat.</param>
        /// <param name="snappedWaypoints">SnappedWaypoints.</param>
        /// <param name="instructions">Instructions.</param>
        /// <param name="details"></param>
        public RouteResponsePath(double? distance = default(double?), long? time = default(long?), double? ascend = default(double?), double? descend = default(double?), ResponseCoordinates points = default(ResponseCoordinates), bool? pointsEncoded = default(bool?), List<double?> bbox = default(List<double?>), ResponseCoordinates snappedWaypoints = default(ResponseCoordinates), ResponseInstructions instructions = default(ResponseInstructions), ResponseDetails details = default(ResponseDetails))
        {
            this.Distance = distance;
            this.Time = time;
            this.Ascend = ascend;
            this.Descend = descend;
            this.Points = points;
            this.PointsEncoded = pointsEncoded;
            this.Bbox = bbox;
            this.SnappedWaypoints = snappedWaypoints;
            this.Instructions = instructions;
            this.Details = details;
        }

        [DataMember(Name = "details", EmitDefaultValue = false)]
        public ResponseDetails Details { get; set; }

        /// <summary>
        /// The total distance of the route, in meter
        /// </summary>
        /// <value>The total distance of the route, in meter</value>
        [DataMember(Name = "distance", EmitDefaultValue = false)]
        public double? Distance { get; set; }

        /// <summary>
        /// The total time of the route, in ms
        /// </summary>
        /// <value>The total time of the route, in ms</value>
        [DataMember(Name = "time", EmitDefaultValue = false)]
        public long? Time { get; set; }

        /// <summary>
        /// Gets or Sets Ascend
        /// </summary>
        [DataMember(Name = "ascend", EmitDefaultValue = false)]
        public double? Ascend { get; set; }

        /// <summary>
        /// The total descend (downhill) of the route, in meter
        /// </summary>
        /// <value>The total descend (downhill) of the route, in meter</value>
        [DataMember(Name = "descend", EmitDefaultValue = false)]
        public double? Descend { get; set; }

        /// <summary>
        /// Gets or Sets Points
        /// </summary>
        [DataMember(Name = "points", EmitDefaultValue = false)]
        public ResponseCoordinates Points { get; set; }

        /// <summary>
        /// Is true if the points are encoded, if not paths[0].points contains the geo json of the path (then order is lon,lat,elevation), which is easier to handle but consumes more bandwidth compared to encoded version
        /// </summary>
        /// <value>Is true if the points are encoded, if not paths[0].points contains the geo json of the path (then order is lon,lat,elevation), which is easier to handle but consumes more bandwidth compared to encoded version</value>
        [DataMember(Name = "points_encoded", EmitDefaultValue = false)]
        public bool? PointsEncoded { get; set; }

        /// <summary>
        /// The bounding box of the route, format &lt;br&gt; minLon, minLat, maxLon, maxLat
        /// </summary>
        /// <value>The bounding box of the route, format &lt;br&gt; minLon, minLat, maxLon, maxLat</value>
        [DataMember(Name = "bbox", EmitDefaultValue = false)]
        public List<double?> Bbox { get; set; }

        /// <summary>
        /// Gets or Sets SnappedWaypoints
        /// </summary>
        [DataMember(Name = "snapped_waypoints", EmitDefaultValue = false)]
        public ResponseCoordinates SnappedWaypoints { get; set; }

        /// <summary>
        /// Gets or Sets Instructions
        /// </summary>
        [DataMember(Name = "instructions", EmitDefaultValue = false)]
        public ResponseInstructions Instructions { get; set; }

        #region IEquatable implements

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RouteResponsePath {\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Ascend: ").Append(Ascend).Append("\n");
            sb.Append("  Descend: ").Append(Descend).Append("\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("  PointsEncoded: ").Append(PointsEncoded).Append("\n");
            sb.Append("  Bbox: ").Append(Bbox).Append("\n");
            sb.Append("  SnappedWaypoints: ").Append(SnappedWaypoints).Append("\n");
            sb.Append("  Instructions: ").Append(Instructions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RouteResponsePath);
        }

        /// <summary>
        /// Returns true if RouteResponsePath instances are equal
        /// </summary>
        /// <param name="input">Instance of RouteResponsePath to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RouteResponsePath input)
        {
            if (input == null)
                return false;

            return
                (
                    Distance == input.Distance ||
                    (Distance != null &&
                    Distance.Equals(input.Distance))
                ) &&
                (
                    Time == input.Time ||
                    (Time != null &&
                    Time.Equals(input.Time))
                ) &&
                (
                    Ascend == input.Ascend ||
                    (Ascend != null &&
                    Ascend.Equals(input.Ascend))
                ) &&
                (
                    Descend == input.Descend ||
                    (Descend != null &&
                    Descend.Equals(input.Descend))
                ) &&
                (
                    Points == input.Points ||
                    (Points != null &&
                    Points.Equals(input.Points))
                ) &&
                (
                    PointsEncoded == input.PointsEncoded ||
                    (PointsEncoded != null &&
                    PointsEncoded.Equals(input.PointsEncoded))
                ) &&
                (
                    Bbox == input.Bbox ||
                    Bbox != null &&
                    Bbox.SequenceEqual(input.Bbox)
                ) &&
                (
                    SnappedWaypoints == input.SnappedWaypoints ||
                    (SnappedWaypoints != null &&
                    SnappedWaypoints.Equals(input.SnappedWaypoints))
                ) &&
                (
                    Instructions == input.Instructions ||
                    (Instructions != null &&
                    Instructions.Equals(input.Instructions))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Distance != null)
                    hashCode = hashCode * 59 + Distance.GetHashCode();
                if (Time != null)
                    hashCode = hashCode * 59 + Time.GetHashCode();
                if (Ascend != null)
                    hashCode = hashCode * 59 + Ascend.GetHashCode();
                if (Descend != null)
                    hashCode = hashCode * 59 + Descend.GetHashCode();
                if (Points != null)
                    hashCode = hashCode * 59 + Points.GetHashCode();
                if (PointsEncoded != null)
                    hashCode = hashCode * 59 + PointsEncoded.GetHashCode();
                if (Bbox != null)
                    hashCode = hashCode * 59 + Bbox.GetHashCode();
                if (SnappedWaypoints != null)
                    hashCode = hashCode * 59 + SnappedWaypoints.GetHashCode();
                if (Instructions != null)
                    hashCode = hashCode * 59 + Instructions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        #endregion
    }

}
