/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// Service
    /// </summary>
    [DataContract]
    public partial class Service :  IEquatable<Service>, IValidatableObject
    {
        /// <summary>
        /// type of service
        /// </summary>
        /// <value>type of service</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum Service for value: service
            /// </summary>
            [EnumMember(Value = "service")]
            Service = 1,
            
            /// <summary>
            /// Enum Pickup for value: pickup
            /// </summary>
            [EnumMember(Value = "pickup")]
            Pickup = 2,
            
            /// <summary>
            /// Enum Delivery for value: delivery
            /// </summary>
            [EnumMember(Value = "delivery")]
            Delivery = 3
        }

        /// <summary>
        /// type of service
        /// </summary>
        /// <value>type of service</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Service" /> class.
        /// </summary>
        /// <param name="Id">Unique identifier of service.</param>
        /// <param name="Type">type of service.</param>
        /// <param name="Priority">priority of service.</param>
        /// <param name="Name">name of service.</param>
        /// <param name="Address">Address.</param>
        /// <param name="Duration">duration of service, i.e. time in seconds the corresponding activity takes.</param>
        /// <param name="PreparationTime">preparation time of service, e.g. search for a parking space. it only falls due if the location of previous activity differs from this location.</param>
        /// <param name="TimeWindows">array of time windows. currently, only a single time window is allowed.</param>
        /// <param name="Size">array of capacity dimensions.</param>
        /// <param name="RequiredSkills">array of required skills.</param>
        /// <param name="AllowedVehicles">array of allowed vehicle ids.</param>
        /// <param name="DisallowedVehicles">array of disallowed vehicle ids.</param>
        /// <param name="MaxTimeInVehicle">max time service can stay in vehicle.</param>
        public Service(string Id = default(string), TypeEnum? Type = default(TypeEnum?), int? Priority = default(int?), string Name = default(string), Address Address = default(Address), long? Duration = default(long?), long? PreparationTime = default(long?), List<TimeWindow> TimeWindows = default(List<TimeWindow>), List<int?> Size = default(List<int?>), List<string> RequiredSkills = default(List<string>), List<string> AllowedVehicles = default(List<string>), List<string> DisallowedVehicles = default(List<string>), long? MaxTimeInVehicle = default(long?))
        {
            this.Id = Id;
            this.Type = Type;
            this.Priority = Priority;
            this.Name = Name;
            this.Address = Address;
            this.Duration = Duration;
            this.PreparationTime = PreparationTime;
            this.TimeWindows = TimeWindows;
            this.Size = Size;
            this.RequiredSkills = RequiredSkills;
            this.AllowedVehicles = AllowedVehicles;
            this.DisallowedVehicles = DisallowedVehicles;
            this.MaxTimeInVehicle = MaxTimeInVehicle;
        }
        
        /// <summary>
        /// Unique identifier of service
        /// </summary>
        /// <value>Unique identifier of service</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }


        /// <summary>
        /// priority of service
        /// </summary>
        /// <value>priority of service</value>
        [DataMember(Name="priority", EmitDefaultValue=false)]
        public int? Priority { get; set; }

        /// <summary>
        /// name of service
        /// </summary>
        /// <value>name of service</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public Address Address { get; set; }

        /// <summary>
        /// duration of service, i.e. time in seconds the corresponding activity takes
        /// </summary>
        /// <value>duration of service, i.e. time in seconds the corresponding activity takes</value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public long? Duration { get; set; }

        /// <summary>
        /// preparation time of service, e.g. search for a parking space. it only falls due if the location of previous activity differs from this location
        /// </summary>
        /// <value>preparation time of service, e.g. search for a parking space. it only falls due if the location of previous activity differs from this location</value>
        [DataMember(Name="preparation_time", EmitDefaultValue=false)]
        public long? PreparationTime { get; set; }

        /// <summary>
        /// array of time windows. currently, only a single time window is allowed
        /// </summary>
        /// <value>array of time windows. currently, only a single time window is allowed</value>
        [DataMember(Name="time_windows", EmitDefaultValue=false)]
        public List<TimeWindow> TimeWindows { get; set; }

        /// <summary>
        /// array of capacity dimensions
        /// </summary>
        /// <value>array of capacity dimensions</value>
        [DataMember(Name="size", EmitDefaultValue=false)]
        public List<int?> Size { get; set; }

        /// <summary>
        /// array of required skills
        /// </summary>
        /// <value>array of required skills</value>
        [DataMember(Name="required_skills", EmitDefaultValue=false)]
        public List<string> RequiredSkills { get; set; }

        /// <summary>
        /// array of allowed vehicle ids
        /// </summary>
        /// <value>array of allowed vehicle ids</value>
        [DataMember(Name="allowed_vehicles", EmitDefaultValue=false)]
        public List<string> AllowedVehicles { get; set; }

        /// <summary>
        /// array of disallowed vehicle ids
        /// </summary>
        /// <value>array of disallowed vehicle ids</value>
        [DataMember(Name="disallowed_vehicles", EmitDefaultValue=false)]
        public List<string> DisallowedVehicles { get; set; }

        /// <summary>
        /// max time service can stay in vehicle
        /// </summary>
        /// <value>max time service can stay in vehicle</value>
        [DataMember(Name="max_time_in_vehicle", EmitDefaultValue=false)]
        public long? MaxTimeInVehicle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Service {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  PreparationTime: ").Append(PreparationTime).Append("\n");
            sb.Append("  TimeWindows: ").Append(TimeWindows).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  RequiredSkills: ").Append(RequiredSkills).Append("\n");
            sb.Append("  AllowedVehicles: ").Append(AllowedVehicles).Append("\n");
            sb.Append("  DisallowedVehicles: ").Append(DisallowedVehicles).Append("\n");
            sb.Append("  MaxTimeInVehicle: ").Append(MaxTimeInVehicle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Service);
        }

        /// <summary>
        /// Returns true if Service instances are equal
        /// </summary>
        /// <param name="input">Instance of Service to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Service input)
        {
            if (input == null)
                return false;

            return 
                (
                    Id == input.Id ||
                    (Id != null &&
                    Id.Equals(input.Id))
                ) && 
                (
                    Type == input.Type ||
                    (Type != null &&
                    Type.Equals(input.Type))
                ) && 
                (
                    Priority == input.Priority ||
                    (Priority != null &&
                    Priority.Equals(input.Priority))
                ) && 
                (
                    Name == input.Name ||
                    (Name != null &&
                    Name.Equals(input.Name))
                ) && 
                (
                    Address == input.Address ||
                    (Address != null &&
                    Address.Equals(input.Address))
                ) && 
                (
                    Duration == input.Duration ||
                    (Duration != null &&
                    Duration.Equals(input.Duration))
                ) && 
                (
                    PreparationTime == input.PreparationTime ||
                    (PreparationTime != null &&
                    PreparationTime.Equals(input.PreparationTime))
                ) && 
                (
                    TimeWindows == input.TimeWindows ||
                    TimeWindows != null &&
                    TimeWindows.SequenceEqual(input.TimeWindows)
                ) && 
                (
                    Size == input.Size ||
                    Size != null &&
                    Size.SequenceEqual(input.Size)
                ) && 
                (
                    RequiredSkills == input.RequiredSkills ||
                    RequiredSkills != null &&
                    RequiredSkills.SequenceEqual(input.RequiredSkills)
                ) && 
                (
                    AllowedVehicles == input.AllowedVehicles ||
                    AllowedVehicles != null &&
                    AllowedVehicles.SequenceEqual(input.AllowedVehicles)
                ) && 
                (
                    DisallowedVehicles == input.DisallowedVehicles ||
                    DisallowedVehicles != null &&
                    DisallowedVehicles.SequenceEqual(input.DisallowedVehicles)
                ) && 
                (
                    MaxTimeInVehicle == input.MaxTimeInVehicle ||
                    (MaxTimeInVehicle != null &&
                    MaxTimeInVehicle.Equals(input.MaxTimeInVehicle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Priority != null)
                    hashCode = hashCode * 59 + Priority.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Address != null)
                    hashCode = hashCode * 59 + Address.GetHashCode();
                if (Duration != null)
                    hashCode = hashCode * 59 + Duration.GetHashCode();
                if (PreparationTime != null)
                    hashCode = hashCode * 59 + PreparationTime.GetHashCode();
                if (TimeWindows != null)
                    hashCode = hashCode * 59 + TimeWindows.GetHashCode();
                if (Size != null)
                    hashCode = hashCode * 59 + Size.GetHashCode();
                if (RequiredSkills != null)
                    hashCode = hashCode * 59 + RequiredSkills.GetHashCode();
                if (AllowedVehicles != null)
                    hashCode = hashCode * 59 + AllowedVehicles.GetHashCode();
                if (DisallowedVehicles != null)
                    hashCode = hashCode * 59 + DisallowedVehicles.GetHashCode();
                if (MaxTimeInVehicle != null)
                    hashCode = hashCode * 59 + MaxTimeInVehicle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
