/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// Solution
    /// </summary>
    [DataContract]
    public partial class Solution :  IEquatable<Solution>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Solution" /> class.
        /// </summary>
        /// <param name="Costs">overall costs of solution.</param>
        /// <param name="Distance">overall travel distance in meters.</param>
        /// <param name="Time">overall transport time in seconds.</param>
        /// <param name="TransportTime">overall transport time in seconds.</param>
        /// <param name="MaxOperationTime">operation time of the longest route in seconds.</param>
        /// <param name="WaitingTime">total waiting time in seconds.</param>
        /// <param name="NoVehicles">number of employed vehicles.</param>
        /// <param name="NoUnassigned">number of jobs that could not be assigned to final solution.</param>
        /// <param name="Routes">An array of routes.</param>
        /// <param name="Unassigned">Unassigned.</param>
        public Solution(int? Costs = default(int?), int? Distance = default(int?), long? Time = default(long?), long? TransportTime = default(long?), long? MaxOperationTime = default(long?), long? WaitingTime = default(long?), int? NoVehicles = default(int?), int? NoUnassigned = default(int?), List<Route> Routes = default(List<Route>), SolutionUnassigned Unassigned = default(SolutionUnassigned))
        {
            this.Costs = Costs;
            this.Distance = Distance;
            this.Time = Time;
            this.TransportTime = TransportTime;
            this.MaxOperationTime = MaxOperationTime;
            this.WaitingTime = WaitingTime;
            this.NoVehicles = NoVehicles;
            this.NoUnassigned = NoUnassigned;
            this.Routes = Routes;
            this.Unassigned = Unassigned;
        }
        
        /// <summary>
        /// overall costs of solution
        /// </summary>
        /// <value>overall costs of solution</value>
        [DataMember(Name="costs", EmitDefaultValue=false)]
        public int? Costs { get; set; }

        /// <summary>
        /// overall travel distance in meters
        /// </summary>
        /// <value>overall travel distance in meters</value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public int? Distance { get; set; }

        /// <summary>
        /// overall transport time in seconds
        /// </summary>
        /// <value>overall transport time in seconds</value>
        [DataMember(Name="time", EmitDefaultValue=false)]
        public long? Time { get; set; }

        /// <summary>
        /// overall transport time in seconds
        /// </summary>
        /// <value>overall transport time in seconds</value>
        [DataMember(Name="transport_time", EmitDefaultValue=false)]
        public long? TransportTime { get; set; }

        /// <summary>
        /// operation time of the longest route in seconds
        /// </summary>
        /// <value>operation time of the longest route in seconds</value>
        [DataMember(Name="max_operation_time", EmitDefaultValue=false)]
        public long? MaxOperationTime { get; set; }

        /// <summary>
        /// total waiting time in seconds
        /// </summary>
        /// <value>total waiting time in seconds</value>
        [DataMember(Name="waiting_time", EmitDefaultValue=false)]
        public long? WaitingTime { get; set; }

        /// <summary>
        /// number of employed vehicles
        /// </summary>
        /// <value>number of employed vehicles</value>
        [DataMember(Name="no_vehicles", EmitDefaultValue=false)]
        public int? NoVehicles { get; set; }

        /// <summary>
        /// number of jobs that could not be assigned to final solution
        /// </summary>
        /// <value>number of jobs that could not be assigned to final solution</value>
        [DataMember(Name="no_unassigned", EmitDefaultValue=false)]
        public int? NoUnassigned { get; set; }

        /// <summary>
        /// An array of routes
        /// </summary>
        /// <value>An array of routes</value>
        [DataMember(Name="routes", EmitDefaultValue=false)]
        public List<Route> Routes { get; set; }

        /// <summary>
        /// Gets or Sets Unassigned
        /// </summary>
        [DataMember(Name="unassigned", EmitDefaultValue=false)]
        public SolutionUnassigned Unassigned { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Solution {\n");
            sb.Append("  Costs: ").Append(Costs).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  TransportTime: ").Append(TransportTime).Append("\n");
            sb.Append("  MaxOperationTime: ").Append(MaxOperationTime).Append("\n");
            sb.Append("  WaitingTime: ").Append(WaitingTime).Append("\n");
            sb.Append("  NoVehicles: ").Append(NoVehicles).Append("\n");
            sb.Append("  NoUnassigned: ").Append(NoUnassigned).Append("\n");
            sb.Append("  Routes: ").Append(Routes).Append("\n");
            sb.Append("  Unassigned: ").Append(Unassigned).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Solution);
        }

        /// <summary>
        /// Returns true if Solution instances are equal
        /// </summary>
        /// <param name="input">Instance of Solution to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Solution input)
        {
            if (input == null)
                return false;

            return 
                (
                    Costs == input.Costs ||
                    (Costs != null &&
                    Costs.Equals(input.Costs))
                ) && 
                (
                    Distance == input.Distance ||
                    (Distance != null &&
                    Distance.Equals(input.Distance))
                ) && 
                (
                    Time == input.Time ||
                    (Time != null &&
                    Time.Equals(input.Time))
                ) && 
                (
                    TransportTime == input.TransportTime ||
                    (TransportTime != null &&
                    TransportTime.Equals(input.TransportTime))
                ) && 
                (
                    MaxOperationTime == input.MaxOperationTime ||
                    (MaxOperationTime != null &&
                    MaxOperationTime.Equals(input.MaxOperationTime))
                ) && 
                (
                    WaitingTime == input.WaitingTime ||
                    (WaitingTime != null &&
                    WaitingTime.Equals(input.WaitingTime))
                ) && 
                (
                    NoVehicles == input.NoVehicles ||
                    (NoVehicles != null &&
                    NoVehicles.Equals(input.NoVehicles))
                ) && 
                (
                    NoUnassigned == input.NoUnassigned ||
                    (NoUnassigned != null &&
                    NoUnassigned.Equals(input.NoUnassigned))
                ) && 
                (
                    Routes == input.Routes ||
                    Routes != null &&
                    Routes.SequenceEqual(input.Routes)
                ) && 
                (
                    Unassigned == input.Unassigned ||
                    (Unassigned != null &&
                    Unassigned.Equals(input.Unassigned))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Costs != null)
                    hashCode = hashCode * 59 + Costs.GetHashCode();
                if (Distance != null)
                    hashCode = hashCode * 59 + Distance.GetHashCode();
                if (Time != null)
                    hashCode = hashCode * 59 + Time.GetHashCode();
                if (TransportTime != null)
                    hashCode = hashCode * 59 + TransportTime.GetHashCode();
                if (MaxOperationTime != null)
                    hashCode = hashCode * 59 + MaxOperationTime.GetHashCode();
                if (WaitingTime != null)
                    hashCode = hashCode * 59 + WaitingTime.GetHashCode();
                if (NoVehicles != null)
                    hashCode = hashCode * 59 + NoVehicles.GetHashCode();
                if (NoUnassigned != null)
                    hashCode = hashCode * 59 + NoUnassigned.GetHashCode();
                if (Routes != null)
                    hashCode = hashCode * 59 + Routes.GetHashCode();
                if (Unassigned != null)
                    hashCode = hashCode * 59 + Unassigned.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
