/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// Vehicle
    /// </summary>
    [DataContract]
    public partial class Vehicle : IEquatable<Vehicle>, IValidatableObject
    {
        private VehicleType _vehicleType;

        /// <summary>
        /// Initializes a new instance of the <see cref="Vehicle" /> class.
        /// </summary>
        /// <param name="vehicleId">Unique identifier of vehicle.</param>
        /// <param name="vehicleType"></param>
        /// <param name="startAddress">StartAddress.</param>
        /// <param name="endAddress">EndAddress.</param>
        /// <param name="Break">Break.</param>
        /// <param name="returnToDepot">Indicates whether vehicle should return to start address or not. If not, it can end at any service activity..</param>
        /// <param name="earliestStart">earliest start of vehicle at its start location.</param>
        /// <param name="latestEnd">latest end of vehicle at its end location.</param>
        /// <param name="skills">array of skills.</param>
        /// <param name="maxDistance">max distance of vehicle.</param>
        /// <param name="maxDrivingTime">max drive time of vehicle.</param>
        /// <param name="maxJobs">max number of jobs the vehicle can load.</param>
        /// <param name="maxActivities">max number of activities the vehicle can conduct.</param>
        public Vehicle(string vehicleId = default(string), VehicleType vehicleType = default(VehicleType), Address startAddress = default(Address), Address endAddress = default(Address), Break Break = default(Break), bool? returnToDepot = default(bool?), long? earliestStart = default(long?), long? latestEnd = default(long?), List<string> skills = default(List<string>), long? maxDistance = default(long?), long? maxDrivingTime = default(long?), int? maxJobs = default(int?), int? maxActivities = default(int?))
        {
            VehicleId = vehicleId;
            VehicleType = vehicleType;
            StartAddress = startAddress;
            EndAddress = endAddress;
            this.Break = Break;
            ReturnToDepot = returnToDepot;
            EarliestStart = earliestStart;
            LatestEnd = latestEnd;
            Skills = skills;
            MaxDistance = maxDistance;
            MaxDrivingTime = maxDrivingTime;
            MaxJobs = maxJobs;
            MaxActivities = maxActivities;
        }

        /// <summary>
        /// Unique identifier of vehicle
        /// </summary>
        /// <value>Unique identifier of vehicle</value>
        [DataMember(Name = "vehicle_id", EmitDefaultValue = false)]
        public string VehicleId { get; set; }

        /// <summary>
        /// Unique identifier referring to the available vehicle types
        /// </summary>
        /// <value>Unique identifier referring to the available vehicle types</value>
        [DataMember(Name = "type_id", EmitDefaultValue = false)]
        public string VehicleTypeId { get; set; }

        public VehicleType VehicleType
        {
            get => _vehicleType;
            set {
                _vehicleType = value;
                //Unique identifier referring to the available vehicle types.
                VehicleTypeId = _vehicleType.TypeId;
            }
        }

        /// <summary>
        /// Gets or Sets StartAddress
        /// </summary>
        [DataMember(Name = "start_address", EmitDefaultValue = false)]
        public Address StartAddress { get; set; }

        /// <summary>
        /// Gets or Sets EndAddress
        /// </summary>
        [DataMember(Name = "end_address", EmitDefaultValue = false)]
        public Address EndAddress { get; set; }

        /// <summary>
        /// Gets or Sets Break
        /// </summary>
        [DataMember(Name = "break", EmitDefaultValue = false)]
        public Break Break { get; set; }

        /// <summary>
        /// Indicates whether vehicle should return to start address or not. If not, it can end at any service activity.
        /// </summary>
        /// <value>Indicates whether vehicle should return to start address or not. If not, it can end at any service activity.</value>
        [DataMember(Name = "return_to_depot", EmitDefaultValue = false)]
        public bool? ReturnToDepot { get; set; }

        /// <summary>
        /// earliest start of vehicle at its start location
        /// </summary>
        /// <value>earliest start of vehicle at its start location</value>
        [DataMember(Name = "earliest_start", EmitDefaultValue = false)]
        public long? EarliestStart { get; set; }

        /// <summary>
        /// latest end of vehicle at its end location
        /// </summary>
        /// <value>latest end of vehicle at its end location</value>
        [DataMember(Name = "latest_end", EmitDefaultValue = false)]
        public long? LatestEnd { get; set; }

        /// <summary>
        /// array of skills
        /// </summary>
        /// <value>array of skills</value>
        [DataMember(Name = "skills", EmitDefaultValue = false)]
        public List<string> Skills { get; set; }

        /// <summary>
        /// max distance of vehicle
        /// </summary>
        /// <value>max distance of vehicle</value>
        [DataMember(Name = "max_distance", EmitDefaultValue = false)]
        public long? MaxDistance { get; set; }

        /// <summary>
        /// max drive time of vehicle
        /// </summary>
        /// <value>max drive time of vehicle</value>
        [DataMember(Name = "max_driving_time", EmitDefaultValue = false)]
        public long? MaxDrivingTime { get; set; }

        /// <summary>
        /// max number of jobs the vehicle can load
        /// </summary>
        /// <value>max number of jobs the vehicle can load</value>
        [DataMember(Name = "max_jobs", EmitDefaultValue = false)]
        public int? MaxJobs { get; set; }

        /// <summary>
        /// max number of activities the vehicle can conduct
        /// </summary>
        /// <value>max number of activities the vehicle can conduct</value>
        [DataMember(Name = "max_activities", EmitDefaultValue = false)]
        public int? MaxActivities { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Vehicle {\n");
            sb.Append("  VehicleId: ").Append(VehicleId).Append("\n");
            sb.Append("  TypeId: ").Append(VehicleTypeId).Append("\n");
            sb.Append("  StartAddress: ").Append(StartAddress).Append("\n");
            sb.Append("  EndAddress: ").Append(EndAddress).Append("\n");
            sb.Append("  Break: ").Append(Break).Append("\n");
            sb.Append("  ReturnToDepot: ").Append(ReturnToDepot).Append("\n");
            sb.Append("  EarliestStart: ").Append(EarliestStart).Append("\n");
            sb.Append("  LatestEnd: ").Append(LatestEnd).Append("\n");
            sb.Append("  Skills: ").Append(Skills).Append("\n");
            sb.Append("  MaxDistance: ").Append(MaxDistance).Append("\n");
            sb.Append("  MaxDrivingTime: ").Append(MaxDrivingTime).Append("\n");
            sb.Append("  MaxJobs: ").Append(MaxJobs).Append("\n");
            sb.Append("  MaxActivities: ").Append(MaxActivities).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Vehicle);
        }

        /// <summary>
        /// Returns true if Vehicle instances are equal
        /// </summary>
        /// <param name="input">Instance of Vehicle to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Vehicle input)
        {
            if (input == null)
                return false;

            return
                (
                    VehicleId == input.VehicleId ||
                    (VehicleId != null &&
                    VehicleId.Equals(input.VehicleId))
                ) &&
                (
                    VehicleTypeId == input.VehicleTypeId ||
                    (VehicleTypeId != null &&
                    VehicleTypeId.Equals(input.VehicleTypeId))
                ) &&
                (
                    StartAddress == input.StartAddress ||
                    (StartAddress != null &&
                    StartAddress.Equals(input.StartAddress))
                ) &&
                (
                    EndAddress == input.EndAddress ||
                    (EndAddress != null &&
                    EndAddress.Equals(input.EndAddress))
                ) &&
                (
                    Break == input.Break ||
                    (Break != null &&
                    Break.Equals(input.Break))
                ) &&
                (
                    ReturnToDepot == input.ReturnToDepot ||
                    (ReturnToDepot != null &&
                    ReturnToDepot.Equals(input.ReturnToDepot))
                ) &&
                (
                    EarliestStart == input.EarliestStart ||
                    (EarliestStart != null &&
                    EarliestStart.Equals(input.EarliestStart))
                ) &&
                (
                    LatestEnd == input.LatestEnd ||
                    (LatestEnd != null &&
                    LatestEnd.Equals(input.LatestEnd))
                ) &&
                (
                    Skills == input.Skills ||
                    Skills != null &&
                    Skills.SequenceEqual(input.Skills)
                ) &&
                (
                    MaxDistance == input.MaxDistance ||
                    (MaxDistance != null &&
                    MaxDistance.Equals(input.MaxDistance))
                ) &&
                (
                    MaxDrivingTime == input.MaxDrivingTime ||
                    (MaxDrivingTime != null &&
                    MaxDrivingTime.Equals(input.MaxDrivingTime))
                ) &&
                (
                    MaxJobs == input.MaxJobs ||
                    (MaxJobs != null &&
                    MaxJobs.Equals(input.MaxJobs))
                ) &&
                (
                    MaxActivities == input.MaxActivities ||
                    (MaxActivities != null &&
                    MaxActivities.Equals(input.MaxActivities))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (VehicleId != null)
                    hashCode = hashCode * 59 + VehicleId.GetHashCode();
                if (VehicleTypeId != null)
                    hashCode = hashCode * 59 + VehicleTypeId.GetHashCode();
                if (StartAddress != null)
                    hashCode = hashCode * 59 + StartAddress.GetHashCode();
                if (EndAddress != null)
                    hashCode = hashCode * 59 + EndAddress.GetHashCode();
                if (Break != null)
                    hashCode = hashCode * 59 + Break.GetHashCode();
                if (ReturnToDepot != null)
                    hashCode = hashCode * 59 + ReturnToDepot.GetHashCode();
                if (EarliestStart != null)
                    hashCode = hashCode * 59 + EarliestStart.GetHashCode();
                if (LatestEnd != null)
                    hashCode = hashCode * 59 + LatestEnd.GetHashCode();
                if (Skills != null)
                    hashCode = hashCode * 59 + Skills.GetHashCode();
                if (MaxDistance != null)
                    hashCode = hashCode * 59 + MaxDistance.GetHashCode();
                if (MaxDrivingTime != null)
                    hashCode = hashCode * 59 + MaxDrivingTime.GetHashCode();
                if (MaxJobs != null)
                    hashCode = hashCode * 59 + MaxJobs.GetHashCode();
                if (MaxActivities != null)
                    hashCode = hashCode * 59 + MaxActivities.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
