/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace SMEAppHouse.Core.GHClientLib.Model
{
    /// <summary>
    /// VehicleType
    /// </summary>
    [DataContract]
    public partial class VehicleType :  IEquatable<VehicleType>, IValidatableObject
    {
        /// <summary>
        /// Profile of vehicle type
        /// </summary>
        /// <value>Profile of vehicle type</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProfileEnum
        {
            
            /// <summary>
            /// Enum Car for value: car
            /// </summary>
            [EnumMember(Value = "car")]
            Car = 1,
            
            /// <summary>
            /// Enum Bike for value: bike
            /// </summary>
            [EnumMember(Value = "bike")]
            Bike = 2,
            
            /// <summary>
            /// Enum Foot for value: foot
            /// </summary>
            [EnumMember(Value = "foot")]
            Foot = 3,
            
            /// <summary>
            /// Enum Hike for value: hike
            /// </summary>
            [EnumMember(Value = "hike")]
            Hike = 4,
            
            /// <summary>
            /// Enum Mtb for value: mtb
            /// </summary>
            [EnumMember(Value = "mtb")]
            Mtb = 5,
            
            /// <summary>
            /// Enum Racingbike for value: racingbike
            /// </summary>
            [EnumMember(Value = "racingbike")]
            Racingbike = 6,
            
            /// <summary>
            /// Enum Scooter for value: scooter
            /// </summary>
            [EnumMember(Value = "scooter")]
            Scooter = 7,
            
            /// <summary>
            /// Enum Truck for value: truck
            /// </summary>
            [EnumMember(Value = "truck")]
            Truck = 8,
            
            /// <summary>
            /// Enum Smalltruck for value: small_truck
            /// </summary>
            [EnumMember(Value = "small_truck")]
            Smalltruck = 9
        }

        /// <summary>
        /// Profile of vehicle type
        /// </summary>
        /// <value>Profile of vehicle type</value>
        [DataMember(Name="profile", EmitDefaultValue=false)]
        public ProfileEnum? Profile { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleType" /> class.
        /// </summary>
        /// <param name="TypeId">Unique identifier for the vehicle type.</param>
        /// <param name="Profile">Profile of vehicle type.</param>
        /// <param name="Capacity">array of capacity dimensions.</param>
        /// <param name="SpeedFactor">speed_factor of vehicle type.</param>
        /// <param name="ServiceTimeFactor">service time factor of vehicle type.</param>
        /// <param name="CostPerMeter">cost parameter per distance unit, here meter is used.</param>
        /// <param name="CostPerSecond">cost parameter per time unit, here second is used.</param>
        /// <param name="CostPerActivation">cost parameter vehicle activation, i.e. fixed costs per vehicle.</param>
        public VehicleType(string TypeId = default(string), ProfileEnum? Profile = default(ProfileEnum?), List<int?> Capacity = default(List<int?>), double? SpeedFactor = default(double?), double? ServiceTimeFactor = default(double?), double? CostPerMeter = default(double?), double? CostPerSecond = default(double?), double? CostPerActivation = default(double?))
        {
            this.TypeId = TypeId;
            this.Profile = Profile;
            this.Capacity = Capacity;
            this.SpeedFactor = SpeedFactor;
            this.ServiceTimeFactor = ServiceTimeFactor;
            this.CostPerMeter = CostPerMeter;
            this.CostPerSecond = CostPerSecond;
            this.CostPerActivation = CostPerActivation;
        }
        
        /// <summary>
        /// Unique identifier for the vehicle type
        /// </summary>
        /// <value>Unique identifier for the vehicle type</value>
        [DataMember(Name="type_id", EmitDefaultValue=false)]
        public string TypeId { get; set; }


        /// <summary>
        /// array of capacity dimensions
        /// </summary>
        /// <value>array of capacity dimensions</value>
        [DataMember(Name="capacity", EmitDefaultValue=false)]
        public List<int?> Capacity { get; set; }

        /// <summary>
        /// speed_factor of vehicle type
        /// </summary>
        /// <value>speed_factor of vehicle type</value>
        [DataMember(Name="speed_factor", EmitDefaultValue=false)]
        public double? SpeedFactor { get; set; }

        /// <summary>
        /// service time factor of vehicle type
        /// </summary>
        /// <value>service time factor of vehicle type</value>
        [DataMember(Name="service_time_factor", EmitDefaultValue=false)]
        public double? ServiceTimeFactor { get; set; }

        /// <summary>
        /// cost parameter per distance unit, here meter is used
        /// </summary>
        /// <value>cost parameter per distance unit, here meter is used</value>
        [DataMember(Name="cost_per_meter", EmitDefaultValue=false)]
        public double? CostPerMeter { get; set; }

        /// <summary>
        /// cost parameter per time unit, here second is used
        /// </summary>
        /// <value>cost parameter per time unit, here second is used</value>
        [DataMember(Name="cost_per_second", EmitDefaultValue=false)]
        public double? CostPerSecond { get; set; }

        /// <summary>
        /// cost parameter vehicle activation, i.e. fixed costs per vehicle
        /// </summary>
        /// <value>cost parameter vehicle activation, i.e. fixed costs per vehicle</value>
        [DataMember(Name="cost_per_activation", EmitDefaultValue=false)]
        public double? CostPerActivation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VehicleType {\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  Capacity: ").Append(Capacity).Append("\n");
            sb.Append("  SpeedFactor: ").Append(SpeedFactor).Append("\n");
            sb.Append("  ServiceTimeFactor: ").Append(ServiceTimeFactor).Append("\n");
            sb.Append("  CostPerMeter: ").Append(CostPerMeter).Append("\n");
            sb.Append("  CostPerSecond: ").Append(CostPerSecond).Append("\n");
            sb.Append("  CostPerActivation: ").Append(CostPerActivation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as VehicleType);
        }

        /// <summary>
        /// Returns true if VehicleType instances are equal
        /// </summary>
        /// <param name="input">Instance of VehicleType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VehicleType input)
        {
            if (input == null)
                return false;

            return 
                (
                    TypeId == input.TypeId ||
                    (TypeId != null &&
                    TypeId.Equals(input.TypeId))
                ) && 
                (
                    Profile == input.Profile ||
                    (Profile != null &&
                    Profile.Equals(input.Profile))
                ) && 
                (
                    Capacity == input.Capacity ||
                    Capacity != null &&
                    Capacity.SequenceEqual(input.Capacity)
                ) && 
                (
                    SpeedFactor == input.SpeedFactor ||
                    (SpeedFactor != null &&
                    SpeedFactor.Equals(input.SpeedFactor))
                ) && 
                (
                    ServiceTimeFactor == input.ServiceTimeFactor ||
                    (ServiceTimeFactor != null &&
                    ServiceTimeFactor.Equals(input.ServiceTimeFactor))
                ) && 
                (
                    CostPerMeter == input.CostPerMeter ||
                    (CostPerMeter != null &&
                    CostPerMeter.Equals(input.CostPerMeter))
                ) && 
                (
                    CostPerSecond == input.CostPerSecond ||
                    (CostPerSecond != null &&
                    CostPerSecond.Equals(input.CostPerSecond))
                ) && 
                (
                    CostPerActivation == input.CostPerActivation ||
                    (CostPerActivation != null &&
                    CostPerActivation.Equals(input.CostPerActivation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (TypeId != null)
                    hashCode = hashCode * 59 + TypeId.GetHashCode();
                if (Profile != null)
                    hashCode = hashCode * 59 + Profile.GetHashCode();
                if (Capacity != null)
                    hashCode = hashCode * 59 + Capacity.GetHashCode();
                if (SpeedFactor != null)
                    hashCode = hashCode * 59 + SpeedFactor.GetHashCode();
                if (ServiceTimeFactor != null)
                    hashCode = hashCode * 59 + ServiceTimeFactor.GetHashCode();
                if (CostPerMeter != null)
                    hashCode = hashCode * 59 + CostPerMeter.GetHashCode();
                if (CostPerSecond != null)
                    hashCode = hashCode * 59 + CostPerSecond.GetHashCode();
                if (CostPerActivation != null)
                    hashCode = hashCode * 59 + CostPerActivation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
